# Generated by Django 5.1.3 on 2024-11-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeplaylist',
            name='channel_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='youtubeplaylist',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
