# Generated by Django 5.1.3 on 2024-11-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_youtubeplaylist_channel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='channel_title',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='description',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='mood',
            field=models.CharField(choices=[('angry', 'Angry'), ('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('surprise', 'Surprise'), ('calm', 'Calm')], default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='thumbnail_url',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='title',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='video_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
